[package]
name = "git-fetch-commits"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.15"
byte-unit = "4.0.17"
tempfile = "3.3.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"